services:
  cache:
    image: redis:8.0-M03-alpine
    container_name: redis-cache-queue
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 01JJJ5J9DPBCESPYASGSY6FT3X
  db:
    image: 'postgres:17-alpine'
    container_name: 'db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app-server:
    container_name: app-server
    build:
      context: ../.
      dockerfile: ./dev/Dockerfile.dev
    volumes:
      - '../src/.:/usr/src/app/src/.'
    ports:
      - '8000:8000'
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    links:
      - cache
      - db
    depends_on:
      - cache
      - db
    environment:
      - PYTHON_ENV=development
      - PORT=8000

      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=01JJJ5J9DPBCESPYASGSY6FT3X
