"""migration

Revision ID: 487a7edc9c63
Revises: 917ed5fc97b2
Create Date: 2025-01-28 07:06:22.904605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.shared .db.pg_sqlalchemy.connection import BaseSqlModel


# revision identifiers, used by Alembic.
revision: str = '487a7edc9c63'
down_revision: Union[str, None] = '917ed5fc97b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('monthly_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###
