"""migration

Revision ID: 917ed5fc97b2
Revises: c59b19b18ed8
Create Date: 2025-01-28 05:05:22.835908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.shared .db.pg_sqlalchemy.connection import BaseSqlModel


# revision identifiers, used by Alembic.
revision: str = '917ed5fc97b2'
down_revision: Union[str, None] = 'c59b19b18ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    # ### end Alembic commands ###
