"""migration

Revision ID: a63899ea67bd
Revises: 446b4044abbb
Create Date: 2025-01-29 01:35:17.202554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.shared .db.pg_sqlalchemy.connection import BaseSqlModel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a63899ea67bd'
down_revision: Union[str, None] = '446b4044abbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('succeed_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_executions')
    # ### end Alembic commands ###
